# Generated by Django 3.1.2 on 2020-10-10 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main',
            name='description',
            field=models.TextField(blank=True, max_length=500, verbose_name='Характеристики'),
        ),
    ]
