# Generated by Django 3.1.2 on 2020-10-10 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_auto_20201011_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main',
            name='description',
            field=models.TextField(blank=True, default='описание', max_length=500, verbose_name='Характеристики'),
        ),
    ]
