# Generated by Django 3.1.2 on 2020-10-10 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_auto_20201011_0014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='main',
            name='description',
        ),
    ]
