# Generated by Django 3.1.2 on 2020-10-10 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_remove_main_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='main',
            old_name='subcategory',
            new_name='subcayegory',
        ),
    ]
