# Generated by Django 3.1.2 on 2020-10-10 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0005_auto_20201011_0016'),
    ]

    operations = [
        migrations.RenameField(
            model_name='main',
            old_name='subcayegory',
            new_name='subcategory',
        ),
    ]
