# Generated by Django 3.1.2 on 2020-10-12 17:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('categories', '0006_auto_20201011_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories.subcategory', verbose_name='подкатегория'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, default='images/avatar.jpg', null=True, upload_to='user_avatars/', verbose_name='Аватарка')),
                ('insta', models.CharField(blank=True, max_length=200, verbose_name='Инстаграм')),
                ('facebook', models.CharField(blank=True, max_length=200, verbose_name='Фейсбук')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
