# Generated by Django 3.1.2 on 2020-10-18 18:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0010_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
